services:
  db:
    image: postgres:16-alpine
    ports:
       - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: selabdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
      image: adminer
      ports:
        - "9000:8080"
volumes:
  pgdata: